version: 1
builder:
  configs:
  - documentation_targets:
    - CLI
    - CodeGenLLVM
    - Core
    - Driver
    - FrontEnd
    - GenerateHyloFileTests
    - HyloModule
    - IR
    - TestUtils
    - Utils

    custom_documentation_parameters: [
    --include-extended-types, --enable-inherited-docs,
    --source-service, github,
    --source-service-base-url, https://github.com/hylo-lang/hylo/blob/main,
    --checkout-path, .
    ]
