name: Build and test

on:
  push:
    branches: [ main, rewrite ]
  pull_request:
    branches: [ main, rewrite ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM
      run : |
        brew install llvm@11
        export PATH=/usr/local/opt/llvm/bin:"${PATH}"
        sudo swift utils/make-pkgconfig.swift

    - name: Build (Debug)
      run: swift build -v -c debug

    - name: Test (Debug)
      run: swift test -v -c debug
