name: Build and test

on:
  push:
    branches: [ main, rewrite ]
  pull_request:
    branches: [ main, rewrite ]

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Swift version 
      run: swift --version

    - name: Resolve
      run: swift package resolve

    - name: Build (Debug)
      run: swift build -v -c debug

    - name: Test (Debug)
      run: swift test -v -c debug
