name: Build and test

on:
  push:
    branches: [ main, rewrite ]
  pull_request:
    branches: [ main, rewrite ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
    - name: Swift version
      run: swift --version
    - name: Dependencies
      run: |
        brew update
        brew install libmarpa
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
