name: Check the format of the Swift code

on:
  push:
    branches: [ main, format-check ]
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    name: Check the format of the code Swift
    runs-on: ubuntu-22.04
    steps:
    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"
    - name: Swift version 
      run: swift --version
    - name: Build swift-format
      uses: mipalgu/install-swift-format@main
      with:
        ref: "5.6"
    - uses: actions/checkout@v3
    - name: Run swift-format on the codebase
      run: swift-format lint --configuration .swift-format.json -s -r -p Sources Tests *.swift
