name: Format check

defaults:
  run:
    shell: bash -eo pipefail {0}

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    name: Format check
    runs-on: ubuntu-latest
    container: swift:5.8
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - run: git config --global core.autocrlf input

    - name: Swift version
      run: swift --version

    - name: Check code format
      run: Tools/run-swift-format.sh -d lint

    - name: Fix permissions to keep cache happy.
      run: |
        chmod -v -R +rX .build | (grep -v "mode of '.*' retained as " || true) | while read -r message; do
          echo "::warning title=Invalid file permissions automatically fixed::$message"
        done
