name: Format check

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - "Docs/**"
      - "**.md"
      - "README.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    name: Format check
    runs-on: ubuntu-latest
    steps:
    - name: Setup swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.7"

    - uses: actions/checkout@v3

    - name: Swift version
      run: swift --version

    - name: Build swift format
      run: swift build -c debug -v --target swift-format && find . -name swift-format

    - name: Check code format
      run: Tools/run-swift-format.sh -d lint
